# Site settings
theme: minima
title: FAEST Signature Algorithm
author: FAEST Team
email: team@faest.info
address: Europe, Earth
description: >-
  The FAEST digital signature algorithm
baseurl: "/"
url: "https://faest.info"
github_username: faest-sign
repository: faest-sign/faest-sign.github.io
markdown: kramdown

# Pages in the navigation bar, in order:
header_pages:
  - components.md
  - resources.md
  - software.md
  - authors.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-spaceship
