# Site settings
theme: minima
title: FAEST-Sign
author: FAEST Team
email: faest.authors@gmail.com
address: Europe, Earth
description: >-
  The FAEST digital signature algorithm
baseurl: "/"
url: "https://faest-sign.github.io"
github_username: faest-sign

# Pages in the navigation bar, in order:
header_pages:
  - components.md
  - resources.md
  - software.md
  - authors.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
